services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: prn232_lms_lab3_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "12433:1433"
    volumes:
      - sqlserver_lab3_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: PRN232.LMS.API/Dockerfile
    container_name: prn232_lms_lab3_api
    ports:
      - "8081:8080"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PRN232_LMS;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"
      Jwt__Secret: "${JWT_SECRET}"

volumes:
  sqlserver_lab3_data:
